# Available placeholders:
# {YEAR}, {MONTH}, {MONTH_NAME}, {DAY}, {HOUR}, {MINUTE}, {SECOND}
# {RANDOM_8} - 8 random characters
# {RANDOM_16} - 16 random chars
outputFileFormat: "log_{DAY}_{MONTH}_{YEAR}"

# Available placeholders:
# {YEAR}, {MONTH}, {MONTH_NAME}, {DAY}, {HOUR}, {MINUTE}, {SECOND}
# {WHO} - Console, RCON, player's name
# {WHAT} - executed command or sent message
# {TYPE} - COMMAND - wher console or rcon executes command , COMMAND_PREPROCESS player command preprocess, ASYNC_CHAT player chat
logFormat: "{YEAR} {MONTH} {DAY} [{HOUR}:{MINUTE}:{SECOND}] {WHO} - {WHAT}"